### ISSUE TITLE
private method `include' called for Swagger::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by rautenberg** [jphastings/sinatra-swagger#3]
Hi,
when starting my application with unicorn I get the following error. 
It seems Base.include(RackHelpers) fails in sinatra-swagger-0.4.1/swagger/rack.rb because it is called outside of the the class Swagger::Base ?

```
E, [2015-04-02T14:00:14.747295 #7955] ERROR -- : private method `include' called for Swagger::Base:Class (NoMethodError)
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/swagger/rack.rb:40:in `<module:Swagger>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/swagger/rack.rb:3:in `<top (required)>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger/swagger_linked.rb:1:in `require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger/swagger_linked.rb:1:in `<top (required)>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger/param_validator.rb:1:in `require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger/param_validator.rb:1:in `<top (required)>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger.rb:2:in `require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sinatra-swagger-0.4.1/lib/sinatra/swagger.rb:2:in `<top (required)>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:81:in `require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:81:in `rescue in block in require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:66:in `block in require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
config.ru:4:in `block in <main>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `call'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:628:in `init_worker_process'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:651:in `worker_loop'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'
/home/blubb/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
/home/blubb/.rbenv/versions/2.0.0-p0/bin/unicorn:23:in `load'
/home/blubb/.rbenv/versions/2.0.0-p0/bin/unicorn:23:in `<main>'
```

**Comment by jphastings** [comment]
This is why I need to get round to actually writing some tests! I'll have broken that yesterday, I'll have a look :)

**Comment by jphastings** [comment]
Do you have a simple application which triggers this problem?

**Comment by rautenberg** [comment]
thanks, that do work in my setup.
